# Generated by Django 5.0.4 on 2024-08-13 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_specification', models.CharField(max_length=300, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artisanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('stat', models.CharField(blank=True, max_length=255, null=True)),
                ('nif', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisanat_responsable', to='Accounts.responsableetablissement')),
            ],
        ),
        migrations.CreateModel(
            name='LocalisationArtisanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('artisanat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localisation_artisanat', to='Artisanal.artisanat')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisanal.panier')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Livré', 'Livré'), ('Annulé', 'Annulé')], default='En attente', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('panier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artisanal.panier')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitArtisanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit_artisanal', models.CharField(default='', max_length=100)),
                ('description_artisanat', models.TextField()),
                ('prix_artisanat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible_artisanat', models.BooleanField(default=True)),
                ('nb_produit_dispo', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisanat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_produit', to='Artisanal.artisanat')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_produits', to=settings.AUTH_USER_MODEL)),
                ('specifications', models.ManyToManyField(related_name='produits_artisanaux', to='Artisanal.specification')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(through='Artisanal.ItemPanier', to='Artisanal.produitartisanal'),
        ),
        migrations.AddField(
            model_name='itempanier',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisanal.produitartisanal'),
        ),
        migrations.CreateModel(
            name='ImageProduitArtisanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couverture', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='images/artisanat_images')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Artisanal.produitartisanal')),
            ],
        ),
        migrations.CreateModel(
            name='AvisClientProduitArtisanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_clients', to='Artisanal.produitartisanal')),
            ],
        ),
    ]
