# Generated by Django 5.0.4 on 2024-08-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanal', '0002_alter_commande_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitartisanal',
            name='hauteur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produitartisanal',
            name='largeur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produitartisanal',
            name='poid_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
