# Generated by Django 5.0.4 on 2024-08-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanal', '0003_produitartisanal_hauteur_produitartisanal_largeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanat',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
