# Generated by Django 5.0.4 on 2024-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanal', '0004_artisanat_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitartisanal',
            name='prix_artisanat',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
