# Generated by Django 5.0.4 on 2024-08-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanal', '0006_transactionartisanat_commandeproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeproduit',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
