# Generated by Django 5.0.4 on 2024-08-23 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanal', '0007_alter_commandeproduit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanat',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5, validators=[django.core.validators.MinValueValidator(7.0), django.core.validators.MaxValueValidator(15.0)]),
        ),
    ]
