# Generated by Django 5.0.4 on 2024-09-12 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisanal', '0008_artisanat_taux_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationArtisanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('artisanat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_artisanat', to='Artisanal.artisanat')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
