# Generated by Django 5.0.4 on 2024-08-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsableetablissement',
            name='ban',
            field=models.BooleanField(default=True),
        ),
    ]
