# Generated by Django 5.0.4 on 2024-08-13 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_inclusion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': "Type d'Inclusion",
                'verbose_name_plural': "Types d'Inclusion",
            },
        ),
        migrations.CreateModel(
            name='TypeTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=100)),
                ('place', models.IntegerField(default=12)),
            ],
            options={
                'verbose_name': 'Type de Transport',
                'verbose_name_plural': 'Types de Transport',
            },
        ),
        migrations.CreateModel(
            name='TourOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_operateur', models.CharField(max_length=100)),
                ('adresse_operateur', models.CharField(blank=True, max_length=255, null=True)),
                ('email_operateur', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone_operateur', models.CharField(blank=True, max_length=10, null=True)),
                ('description_operateur', models.TextField(blank=True, null=True)),
                ('stat', models.CharField(blank=True, max_length=255, null=True)),
                ('nif', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_TourOperateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourOperateur', to='Accounts.responsableetablissement')),
            ],
            options={
                'verbose_name': 'Tour Operateur',
                'verbose_name_plural': 'Tour Operateurs',
            },
        ),
        migrations.CreateModel(
            name='LocalisationTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tour_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localisation_tour', to='TourOperateur.touroperateur')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/images_tour')),
                ('couverture', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_tour', to='TourOperateur.touroperateur')),
            ],
            options={
                'verbose_name': 'Image Tour',
                'verbose_name_plural': 'Images Tour',
            },
        ),
        migrations.CreateModel(
            name='AvisTourOperateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour_operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_tour_operateur', to='TourOperateur.touroperateur')),
            ],
            options={
                'verbose_name': 'Avis Tour Operateur',
                'verbose_name_plural': 'Avis Tour Operateurs',
                'ordering': ['-date_avis'],
            },
        ),
        migrations.CreateModel(
            name='InclusionVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_inclusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voyage_part', to='TourOperateur.typeinclusion')),
            ],
            options={
                'verbose_name': 'Inclusion Voyage',
                'verbose_name_plural': 'Inclusions Voyage',
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_voyage', models.CharField(max_length=100)),
                ('ville_depart', models.CharField(default='Antananarivo', max_length=100)),
                ('destination_voyage', models.CharField(max_length=255)),
                ('description_voyage', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('distance', models.IntegerField(null=True)),
                ('prix_voyage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('places_disponibles', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inclusions', models.ManyToManyField(blank=True, related_name='voyages', to='TourOperateur.typeinclusion')),
                ('tour_operateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='TourOperateur.touroperateur')),
                ('type_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_transport', to='TourOperateur.typetransport')),
            ],
            options={
                'verbose_name': 'Voyage',
                'verbose_name_plural': 'Voyages',
            },
        ),
        migrations.CreateModel(
            name='TrajetVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_trajet', models.IntegerField(blank=True, null=True)),
                ('nom_ville', models.CharField(max_length=250, null=True)),
                ('date_trajet', models.DateField(blank=True, null=True)),
                ('description_trajet', models.CharField(blank=True, max_length=1000, null=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyage_trajet', to='TourOperateur.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation_voyage', models.DateTimeField(auto_now_add=True)),
                ('nombre_voyageurs', models.IntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmée'), ('pending', 'En attente'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='TourOperateur.voyage')),
            ],
            options={
                'verbose_name': 'Reservation Voyage',
                'verbose_name_plural': 'Reservations Voyage',
            },
        ),
        migrations.CreateModel(
            name='ImageVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/images_voyage')),
                ('couverture', models.BooleanField(default=False)),
                ('image_voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_voyage', to='TourOperateur.voyage')),
            ],
            options={
                'verbose_name': 'Image Voyage',
                'verbose_name_plural': 'Images Voyage',
            },
        ),
        migrations.CreateModel(
            name='SatisfactionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_satisfait', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_satisfaction', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_satisfaction', to='TourOperateur.touroperateur')),
            ],
            options={
                'verbose_name': 'Satisfaction Client',
                'verbose_name_plural': 'Satisfactions Clients',
                'unique_together': {('client', 'tour')},
            },
        ),
        migrations.CreateModel(
            name='VoyageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='TourOperateur.voyage')),
            ],
            options={
                'verbose_name': 'Voyage Like',
                'verbose_name_plural': 'Voyage Likes',
                'unique_together': {('voyage', 'client')},
            },
        ),
    ]
