# Generated by Django 5.0.4 on 2024-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourOperateur', '0002_alter_reservationvoyage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationvoyage',
            name='prix_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationvoyage',
            name='nombre_voyageurs',
            field=models.IntegerField(default=1),
        ),
    ]
