# Generated by Django 5.0.4 on 2024-08-13 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoireChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_accessoire', models.CharField(max_length=100)),
                ('description_accessoire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoireHebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_accessoire', models.CharField(max_length=100)),
                ('description_accessoire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chambre', models.CharField(max_length=100)),
                ('nombre_min_personnes', models.IntegerField(default=1)),
                ('nombre_max_personnes', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ChambrePersonaliser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chambre', models.CharField(max_length=100)),
                ('nombre_personnes', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeHebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hebergement', models.CharField(max_length=100)),
                ('description_hebergement', models.TextField(blank=True, null=True)),
                ('nombre_etoile_hebergement', models.IntegerField(blank=True, null=True)),
                ('nif', models.CharField(blank=True, max_length=100, null=True)),
                ('stat', models.CharField(blank=True, max_length=100, null=True)),
                ('autorisation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_hebergement', to=settings.AUTH_USER_MODEL)),
                ('responsable_hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hebergements', to='Accounts.responsableetablissement')),
                ('type_hebergement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Hebergement.typehebergement')),
            ],
        ),
        migrations.CreateModel(
            name='AvisClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=500, null=True)),
                ('note', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_client', to=settings.AUTH_USER_MODEL)),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_hotel', to='Hebergement.hebergement')),
            ],
        ),
        migrations.CreateModel(
            name='HebergementAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.accessoirehebergement')),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessoires', to='Hebergement.hebergement')),
            ],
        ),
        migrations.CreateModel(
            name='HebergementChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chambre', models.CharField(default=0, max_length=120)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('superficie', models.IntegerField(blank=True, null=True)),
                ('prix_nuit_chambre', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponible_chambre', models.IntegerField(null=True)),
                ('capacite', models.IntegerField(null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hebergement.chambre')),
                ('chambre_personaliser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hebergement.chambrepersonaliser')),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.hebergement')),
            ],
        ),
        migrations.CreateModel(
            name='HebergementChambreAccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('accessoire_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.accessoirechambre')),
                ('hebergement_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hebergement.hebergementchambre')),
            ],
        ),
        migrations.AddField(
            model_name='hebergementchambre',
            name='accessoires',
            field=models.ManyToManyField(through='Hebergement.HebergementChambreAccessoire', to='Hebergement.accessoirechambre'),
        ),
        migrations.CreateModel(
            name='HebergementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couverture', models.BooleanField(default=False)),
                ('legende_hebergement', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(null=True, upload_to='images/images_Hebergement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Hebergement.hebergement')),
            ],
        ),
        migrations.CreateModel(
            name='ImageChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/images_chambre')),
                ('couverture', models.BooleanField(default=False)),
                ('legende_chambre', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hebergement_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_chambre', to='Hebergement.hebergementchambre')),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('hebergement_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localisation', to='Hebergement.hebergement')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_reserve', models.DateField()),
                ('date_fin_reserve', models.DateField()),
                ('nombre_personnes_reserve', models.IntegerField(default=1)),
                ('prix_total_reserve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_validee_reserve', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chambre_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_chambre', to='Hebergement.hebergementchambre')),
                ('client_reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_client', to=settings.AUTH_USER_MODEL)),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_hotel', to='Hebergement.hebergement')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to='Hebergement.hebergement')),
            ],
        ),
        migrations.AddField(
            model_name='accessoirehebergement',
            name='type_accessoire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hebergement.typeaccessoire'),
        ),
    ]
