# Generated by Django 5.0.4 on 2024-09-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0005_hebergement_taux_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebergementchambre',
            name='disponible_chambre',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
