# Generated by Django 5.0.4 on 2024-09-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hebergement', '0006_alter_hebergementchambre_disponible_chambre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nombre_chambre_reserve',
            field=models.IntegerField(default=1),
        ),
    ]
